name: Gradle Wrapper Validation

on:
  push:
  pull_request:
jobs:
  validation:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Install Java 17
        uses: actions/setup-java@v3.9.0
        with:
          java-version: 17 # Can be more specific if neccesary
          distribution: adopt
      - name: Build
        run: ./gradlew build
      - name: Upload jars
        uses: actions/upload-artifact@v3
        with:
          name: jars
          path: build/libs
          if-no-files-found: error
